#
# (C) Copyright 2015 Seco
# (C) Copyright 2016 Christian Ege
#
# Author: Davide Cardillo <davide.cardillo@seco.com>
# Author: Christian Ege <k4230r6@gmail.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y                            := a62.o 
obj-$(CONFIG_SPL_BUILD)  	 += spl.o 
